on:
  push:
    branches:
    - ASPServer

env:
  DOTNET_CORE_VERSION: 8.0.x
  CONTAINER_APP_NAME: myapp-asplinuxapi   # <= 이름 규칙 맞게 수정
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv20250921173428
  RESOURCE_GROUP: managedEnv20250921173428ResourceGroup
  CONTAINER_REGISTRY_NAME: registry20250921174445
  CONTAINER_REGISTRY_LOGIN_SERVER: registry20250921174445.azurecr.io

jobs:
  BuildAndDeployContainerApp:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.MANAGEDENV20250921173428_SPN }}

    - name: Container App deploy
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
        acrUsername: ${{ secrets.REGISTRY20250921174445_USERNAME_5028 }}
        acrPassword: ${{ secrets.REGISTRY20250921174445_PASSWORD_5028 }}
        imageToBuild: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENVIRONMENT_NAME }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
